[package]
name = "activad-11"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["sync", "rt", "time", "macros", "rt-multi-thread"] }
tokio-macros = "2.4.0"

[features]
one-thread = []
no-sleep = []
